# Generated by Django 5.0.7 on 2024-07-12 09:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_alter_items_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='size',
            field=models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
    ]
